version: "3"

services:
  exercise:
    image: python-exercise
    container_name: python-excercise-${ENVIRONMENT}
    build:
      context: .
      target: ${ENVIRONMENT}
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/opt/python-exercise
    # environment:
    #   ENVIRONMENT: ${ENVIRONMENT}
